// Palette data structure
// Each palette contains named color primitives organized by hue
const palettes = [
    {
        id: 'midnight-canvas',
        name: 'Midnight Canvas',
        description: 'Deep, sophisticated tones for elegant interfaces',
        colors: {
            primary: [
                { name: 'primary-50', hex: '#eef2ff' },
                { name: 'primary-100', hex: '#e0e7ff' },
                { name: 'primary-200', hex: '#c7d2fe' },
                { name: 'primary-300', hex: '#a5b4fc' },
                { name: 'primary-400', hex: '#818cf8' },
                { name: 'primary-500', hex: '#6366f1' },
                { name: 'primary-600', hex: '#4f46e5' },
                { name: 'primary-700', hex: '#4338ca' },
                { name: 'primary-800', hex: '#3730a3' },
                { name: 'primary-900', hex: '#312e81' },
            ],
            secondary: [
                { name: 'secondary-50', hex: '#faf5ff' },
                { name: 'secondary-100', hex: '#f3e8ff' },
                { name: 'secondary-200', hex: '#e9d5ff' },
                { name: 'secondary-300', hex: '#d8b4fe' },
                { name: 'secondary-400', hex: '#c084fc' },
                { name: 'secondary-500', hex: '#a855f7' },
                { name: 'secondary-600', hex: '#9333ea' },
                { name: 'secondary-700', hex: '#7e22ce' },
                { name: 'secondary-800', hex: '#6b21a8' },
                { name: 'secondary-900', hex: '#581c87' },
            ],
            neutral: [
                { name: 'neutral-50', hex: '#fafafa' },
                { name: 'neutral-100', hex: '#f4f4f5' },
                { name: 'neutral-200', hex: '#e4e4e7' },
                { name: 'neutral-300', hex: '#d4d4d8' },
                { name: 'neutral-400', hex: '#a1a1aa' },
                { name: 'neutral-500', hex: '#71717a' },
                { name: 'neutral-600', hex: '#52525b' },
                { name: 'neutral-700', hex: '#3f3f46' },
                { name: 'neutral-800', hex: '#27272a' },
                { name: 'neutral-900', hex: '#18181b' },
            ],
        },
    },
    {
        id: 'ocean-breeze',
        name: 'Ocean Breeze',
        description: 'Calm, refreshing blues and teals for serene designs',
        colors: {
            primary: [
                { name: 'primary-50', hex: '#ecfeff' },
                { name: 'primary-100', hex: '#cffafe' },
                { name: 'primary-200', hex: '#a5f3fc' },
                { name: 'primary-300', hex: '#67e8f9' },
                { name: 'primary-400', hex: '#22d3ee' },
                { name: 'primary-500', hex: '#06b6d4' },
                { name: 'primary-600', hex: '#0891b2' },
                { name: 'primary-700', hex: '#0e7490' },
                { name: 'primary-800', hex: '#155e75' },
                { name: 'primary-900', hex: '#164e63' },
            ],
            secondary: [
                { name: 'secondary-50', hex: '#f0fdfa' },
                { name: 'secondary-100', hex: '#ccfbf1' },
                { name: 'secondary-200', hex: '#99f6e4' },
                { name: 'secondary-300', hex: '#5eead4' },
                { name: 'secondary-400', hex: '#2dd4bf' },
                { name: 'secondary-500', hex: '#14b8a6' },
                { name: 'secondary-600', hex: '#0d9488' },
                { name: 'secondary-700', hex: '#0f766e' },
                { name: 'secondary-800', hex: '#115e59' },
                { name: 'secondary-900', hex: '#134e4a' },
            ],
            neutral: [
                { name: 'neutral-50', hex: '#f8fafc' },
                { name: 'neutral-100', hex: '#f1f5f9' },
                { name: 'neutral-200', hex: '#e2e8f0' },
                { name: 'neutral-300', hex: '#cbd5e1' },
                { name: 'neutral-400', hex: '#94a3b8' },
                { name: 'neutral-500', hex: '#64748b' },
                { name: 'neutral-600', hex: '#475569' },
                { name: 'neutral-700', hex: '#334155' },
                { name: 'neutral-800', hex: '#1e293b' },
                { name: 'neutral-900', hex: '#0f172a' },
            ],
        },
    },
    {
        id: 'sunset-glow',
        name: 'Sunset Glow',
        description: 'Warm, vibrant oranges and pinks for energetic interfaces',
        colors: {
            primary: [
                { name: 'primary-50', hex: '#fff7ed' },
                { name: 'primary-100', hex: '#ffedd5' },
                { name: 'primary-200', hex: '#fed7aa' },
                { name: 'primary-300', hex: '#fdba74' },
                { name: 'primary-400', hex: '#fb923c' },
                { name: 'primary-500', hex: '#f97316' },
                { name: 'primary-600', hex: '#ea580c' },
                { name: 'primary-700', hex: '#c2410c' },
                { name: 'primary-800', hex: '#9a3412' },
                { name: 'primary-900', hex: '#7c2d12' },
            ],
            secondary: [
                { name: 'secondary-50', hex: '#fdf2f8' },
                { name: 'secondary-100', hex: '#fce7f3' },
                { name: 'secondary-200', hex: '#fbcfe8' },
                { name: 'secondary-300', hex: '#f9a8d4' },
                { name: 'secondary-400', hex: '#f472b6' },
                { name: 'secondary-500', hex: '#ec4899' },
                { name: 'secondary-600', hex: '#db2777' },
                { name: 'secondary-700', hex: '#be185d' },
                { name: 'secondary-800', hex: '#9f1239' },
                { name: 'secondary-900', hex: '#831843' },
            ],
            accent: [
                { name: 'accent-50', hex: '#fefce8' },
                { name: 'accent-100', hex: '#fef9c3' },
                { name: 'accent-200', hex: '#fef08a' },
                { name: 'accent-300', hex: '#fde047' },
                { name: 'accent-400', hex: '#facc15' },
                { name: 'accent-500', hex: '#eab308' },
                { name: 'accent-600', hex: '#ca8a04' },
                { name: 'accent-700', hex: '#a16207' },
                { name: 'accent-800', hex: '#854d0e' },
                { name: 'accent-900', hex: '#713f12' },
            ],
            neutral: [
                { name: 'neutral-50', hex: '#fafaf9' },
                { name: 'neutral-100', hex: '#f5f5f4' },
                { name: 'neutral-200', hex: '#e7e5e4' },
                { name: 'neutral-300', hex: '#d6d3d1' },
                { name: 'neutral-400', hex: '#a8a29e' },
                { name: 'neutral-500', hex: '#78716c' },
                { name: 'neutral-600', hex: '#57534e' },
                { name: 'neutral-700', hex: '#44403c' },
                { name: 'neutral-800', hex: '#292524' },
                { name: 'neutral-900', hex: '#1c1917' },
            ],
        },
    },
    {
        id: 'forest-whisper',
        name: 'Forest Whisper',
        description: 'Natural greens and earth tones for organic, grounded designs',
        colors: {
            primary: [
                { name: 'primary-50', hex: '#f0fdf4' },
                { name: 'primary-100', hex: '#dcfce7' },
                { name: 'primary-200', hex: '#bbf7d0' },
                { name: 'primary-300', hex: '#86efac' },
                { name: 'primary-400', hex: '#4ade80' },
                { name: 'primary-500', hex: '#22c55e' },
                { name: 'primary-600', hex: '#16a34a' },
                { name: 'primary-700', hex: '#15803d' },
                { name: 'primary-800', hex: '#166534' },
                { name: 'primary-900', hex: '#14532d' },
            ],
            secondary: [
                { name: 'secondary-50', hex: '#f7fee7' },
                { name: 'secondary-100', hex: '#ecfccb' },
                { name: 'secondary-200', hex: '#d9f99d' },
                { name: 'secondary-300', hex: '#bef264' },
                { name: 'secondary-400', hex: '#a3e635' },
                { name: 'secondary-500', hex: '#84cc16' },
                { name: 'secondary-600', hex: '#65a30d' },
                { name: 'secondary-700', hex: '#4d7c0f' },
                { name: 'secondary-800', hex: '#3f6212' },
                { name: 'secondary-900', hex: '#365314' },
            ],
            neutral: [
                { name: 'neutral-50', hex: '#fafaf9' },
                { name: 'neutral-100', hex: '#f5f5f4' },
                { name: 'neutral-200', hex: '#e7e5e4' },
                { name: 'neutral-300', hex: '#d6d3d1' },
                { name: 'neutral-400', hex: '#a8a29e' },
                { name: 'neutral-500', hex: '#78716c' },
                { name: 'neutral-600', hex: '#57534e' },
                { name: 'neutral-700', hex: '#44403c' },
                { name: 'neutral-800', hex: '#292524' },
                { name: 'neutral-900', hex: '#1c1917' },
            ],
        },
    },
    {
        id: 'cherry-blossom',
        name: 'Cherry Blossom',
        description: 'Soft pinks and purples for delicate, feminine designs',
        colors: {
            primary: [
                { name: 'primary-50', hex: '#fdf2f8' },
                { name: 'primary-100', hex: '#fce7f3' },
                { name: 'primary-200', hex: '#fbcfe8' },
                { name: 'primary-300', hex: '#f9a8d4' },
                { name: 'primary-400', hex: '#f472b6' },
                { name: 'primary-500', hex: '#ec4899' },
                { name: 'primary-600', hex: '#db2777' },
                { name: 'primary-700', hex: '#be185d' },
                { name: 'primary-800', hex: '#9f1239' },
                { name: 'primary-900', hex: '#831843' },
            ],
            secondary: [
                { name: 'secondary-50', hex: '#fef1f7' },
                { name: 'secondary-100', hex: '#fee5f0' },
                { name: 'secondary-200', hex: '#fccce3' },
                { name: 'secondary-300', hex: '#faa2cd' },
                { name: 'secondary-400', hex: '#f569ad' },
                { name: 'secondary-500', hex: '#ea3a8f' },
                { name: 'secondary-600', hex: '#d61b6f' },
                { name: 'secondary-700', hex: '#b81359' },
                { name: 'secondary-800', hex: '#98144a' },
                { name: 'secondary-900', hex: '#7e1541' },
            ],
            neutral: [
                { name: 'neutral-50', hex: '#fafafa' },
                { name: 'neutral-100', hex: '#f5f5f5' },
                { name: 'neutral-200', hex: '#eeeeee' },
                { name: 'neutral-300', hex: '#e0e0e0' },
                { name: 'neutral-400', hex: '#bdbdbd' },
                { name: 'neutral-500', hex: '#9e9e9e' },
                { name: 'neutral-600', hex: '#757575' },
                { name: 'neutral-700', hex: '#616161' },
                { name: 'neutral-800', hex: '#424242' },
                { name: 'neutral-900', hex: '#212121' },
            ],
        },
    },
    {
        id: 'arctic-aurora',
        name: 'Arctic Aurora',
        description: 'Cool blues and whites with subtle gradients for clean, modern interfaces',
        colors: {
            primary: [
                { name: 'primary-50', hex: '#eff6ff' },
                { name: 'primary-100', hex: '#dbeafe' },
                { name: 'primary-200', hex: '#bfdbfe' },
                { name: 'primary-300', hex: '#93c5fd' },
                { name: 'primary-400', hex: '#60a5fa' },
                { name: 'primary-500', hex: '#3b82f6' },
                { name: 'primary-600', hex: '#2563eb' },
                { name: 'primary-700', hex: '#1d4ed8' },
                { name: 'primary-800', hex: '#1e40af' },
                { name: 'primary-900', hex: '#1e3a8a' },
            ],
            secondary: [
                { name: 'secondary-50', hex: '#f0f9ff' },
                { name: 'secondary-100', hex: '#e0f2fe' },
                { name: 'secondary-200', hex: '#bae6fd' },
                { name: 'secondary-300', hex: '#7dd3fc' },
                { name: 'secondary-400', hex: '#38bdf8' },
                { name: 'secondary-500', hex: '#0ea5e9' },
                { name: 'secondary-600', hex: '#0284c7' },
                { name: 'secondary-700', hex: '#0369a1' },
                { name: 'secondary-800', hex: '#075985' },
                { name: 'secondary-900', hex: '#0c4a6e' },
            ],
            neutral: [
                { name: 'neutral-50', hex: '#f9fafb' },
                { name: 'neutral-100', hex: '#f3f4f6' },
                { name: 'neutral-200', hex: '#e5e7eb' },
                { name: 'neutral-300', hex: '#d1d5db' },
                { name: 'neutral-400', hex: '#9ca3af' },
                { name: 'neutral-500', hex: '#6b7280' },
                { name: 'neutral-600', hex: '#4b5563' },
                { name: 'neutral-700', hex: '#374151' },
                { name: 'neutral-800', hex: '#1f2937' },
                { name: 'neutral-900', hex: '#111827' },
            ],
        },
    },
];
